### ISSUE TITLE
Tracking: migrate doc build artifacts from github to hf hub

### ISSUE THREAD

**Issue by mishig25** [huggingface/doc-builder#316]
## Tracking: migrate doc build artifacts from github to hf hub

Why: because hf hub can handle large files & huggingface_hub python client library makes it easy to work with. (With github, we had to almost write python client from scratch using github graphql)

#### Dev Steps:
- [x] Create hf hub org & repos https://huggingface.co/hf-doc-build
- [x] Implement doc-builder changes https://github.com/huggingface/doc-builder/pull/315
    - [x] test on hf-docs https://github.com/huggingface/hub-docs/pull/449
    - [x] test on transformers https://github.com/huggingface/transformers/pull/19867
    - [x] test on transformers main https://github.com/huggingface/transformers/pull/20092
    - [ ] test deletion, by closing a pr build
- [x] Implement hub backend changes https://github.com/huggingface/moon-landing/pull/4249
- [x] Handle credentials/tokens
    - [ ] update `secrets.HUGGINGFACE_PUSH ` token on all repos (for example, [here](https://github.com/huggingface/accelerate/blob/main/.github/workflows/build_documentation.yml#L17))
    - [ ] doc-build-pr.yml will be using `secrets.HUGGINGFACE_PUSH ` as well. Therefore, all the repos should update its doc-build-pr.yml tp supply the token
- [x] Migrate/copy all existing docs from github to hf hub
- [x] Revert dev log changes in https://github.com/huggingface/doc-builder/pull/315

#### Migration Steps:
- [x] Revert dev changes in https://github.com/huggingface/doc-builder/pull/315 : use token & revert branch to main
- [x] in hub backend, `rm -rf doc-build doc-build-dev`
- [x] run `sync-github-repos.js`

#### Resources: 
[internal slack discussion](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1666290578321509)

**Comment by coyotte508** [comment]
If I understand it correctly, for now the repo structure stays the same (no LFS files, no zip), this issue is just moving the repo from github to HF hub

**Comment by coyotte508** [comment]
LFS would still make the repos a lot smaller in size so it should be beneficial in any case.

I didn't see the `gitattributes` :) What's left I guess is on the hub side, making sure to `git lfs install` after cloning the repos.

**Comment by mishig25** [comment]
@coyotte508 I've actually switched to using zipped file. 
When I tried on transformers docs builds (95MB), hub_client was [failing](https://github.com/huggingface/transformers/actions/runs/3319951930/jobs/5486173258#step:11:24) with:
```
File "/usr/local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line [21](https://github.com/huggingface/transformers/actions/runs/3319951930/jobs/5486173258#step:11:22)3, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/datasets/hf-doc-build/doc-build-dev.git/info/lfs/objects/batch
```
cc: @Wauplin 

When I zipped it into a zip file (14 MB), everything [worked](https://github.com/huggingface/transformers/actions/runs/3319951930). You can find on the hub [here](https://huggingface.co/datasets/hf-doc-build/doc-build-dev/blob/main/transformers-pr_19867.zip)

**Comment by mishig25** [comment]
all done
