### ISSUE TITLE
TODOs for completing the updated preprocessors

### ISSUE THREAD

**Issue by mishig25** [huggingface/doc-builder#424]
## TODOs for completing the updated preprocessors
- [ ] refactors the big `preprocess.js` file into multiple files by different preprocessors and add tests to each preprocessor to prevent regression
- [ ] support the disable frontmatter flag
- [ ] check that the headings start with H1 element

we already have #401, #423
